name: starlight_dart_socket_io
description: starlight_dart_socket_io is a dart base socket server that can be used as socket io.
version: 0.0.1
homepage: https://github.com/YeMyoAung/starlight_dart_socket_io.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
